version: '3.5'
services:
    grafana:
        build: grafana/
        image: "lancekuo/grafana:5.0.4-1"
        environment:
            - "GF_SECURITY_ADMIN_PASSWORD=test"
        ports:
            - "3000:3000"
        networks: 
            - monitor-network
        deploy:
            placement:
                constraints:
                    - node.labels.type == internal
            resources:
                limits:
                    cpus: '0.50'
                    memory: 64M
                reservations:
                    cpus: '0.50'
                    memory: 32M
    prometheus:
        build: prometheus/
        image: "lancekuo/prometheus:2.2.1-2"
        volumes:
            - "/opt/prometheus:/prometheus"
        ports:
            - "9090:9090"
        networks: 
            - monitor-network
        deploy:
            placement:
                constraints:
                    - node.labels.type == storage
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1024M
                reservations:
                    cpus: '0.50'
                    memory: 128M
    node:
        build: node-exporter/
        image: "lancekuo/node-exporter:0.15.2"
        command: 
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
            - '--collector.textfile.directory=/etc/node-exporter/'
        volumes:
            - /proc:/host/proc
            - /sys:/host/sys
            - /:/rootfs
            - /etc/hostname:/etc/host_hostname
        environment:
            - "HOST_HOSTNAME=/etc/host_hostname"
        networks: 
            - monitor-network
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 10s
            update_config:
                parallelism: 2
                delay: 10s
            resources:
                limits:
                    cpus: '0.10'
                    memory: 32M
                reservations:
                    cpus: '0.10'
                    memory: 16M

    cadvisor:
        image: "google/cadvisor:v0.29.0"
        volumes:
            - /var/lib/docker:/var/lib/docker
            - /var/run:/var/run
            - /sys:/sys
            - /:/rootfs
        networks: 
            - monitor-network
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 10s
            update_config:
                parallelism: 2
                delay: 10s
            resources:
                limits:
                    cpus: '0.10'
                    memory: 128M
                reservations:
                    cpus: '0.10'
                    memory: 64M
    proxy:
        image: dockerflow/docker-flow-proxy:18.04.16-36-linux-amd64
        environment:
          - LISTENER_ADDRESS=swarm-listener
          - MODE=swarm
        networks:
            - monitor-network
            - app-network
        ports:
            - "80:80"
            - "443:443"
        deploy:
          replicas: 2

    swarm-listener:
        image: dockerflow/docker-flow-swarm-listener:18.04.15-5-linux-amd64
        environment:
          - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
          - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
        networks:
            - monitor-network
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints:
                    - node.role == manager
networks:
  monitor-network:
    external: true
    name: monitor-network
  app-network:
    external: true
    name: app-network
