version: '3.5'
services:
    grafana:
        build: grafana/
        image: "lancekuo/grafana:5.1.3-0"
        environment:
            - "GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}"
            - "GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-test}"
            - "GF_USERS_ALLOW_SIGN_UP=false"
            - "GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-localhost}"
            - "GF_SMTP_ENABLED=${GF_SMTP_ENABLED:-false}"
            - "GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS:-grafana@lancekuo.com}"
            - "GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME:-Grafana}"
            - "GF_SMTP_HOST=${GF_SMTP_HOST:-smtp:25}"
            - "GF_SMTP_USER=${GF_SMTP_USER}"
            - "GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}"
            - "GF_AUTH_GITHUB_ENABLED=${GF_AUTH_GITHUB_ENABLED:-false}"
            - "GF_AUTH_GITHUB_CLIENT_ID=${GF_AUTH_GITHUB_CLIENT_ID}"
            - "GF_AUTH_GITHUB_CLIENT_SECRET=${GF_AUTH_GITHUB_CLIENT_SECRET}"
            - "GF_AUTH_GITHUB_TEAM_IDS=${GF_AUTH_GITHUB_TEAM_IDS}"
            - "GF_AUTH_GITHUB_SCOPES=user:email,read:org"
        ports:
            - "3000:3000"
        networks: 
            - monitor-network
        deploy:
            placement:
                constraints:
                    - node.labels.type == internal
            resources:
                limits:
                    cpus: '0.50'
                    memory: 128M
                reservations:
                    cpus: '0.50'
                    memory: 32M
    prometheus:
        build: prometheus/
        image: "lancekuo/prometheus:2.2.1-2"
        volumes:
            - "/opt/prometheus:/prometheus"
        ports:
            - "9090:9090"
        networks: 
            - monitor-network
        deploy:
            placement:
                constraints:
                    - node.labels.type == storage
            resources:
                limits:
                    cpus: '0.50'
                    memory: 2048M
                reservations:
                    cpus: '0.50'
                    memory: 128M
    node:
        build: node-exporter/
        image: "lancekuo/node-exporter:0.15.2"
        command: 
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
            - '--collector.textfile.directory=/etc/node-exporter/'
        volumes:
            - /proc:/host/proc
            - /sys:/host/sys
            - /:/rootfs
            - /etc/hostname:/etc/host_hostname
        environment:
            - "HOST_HOSTNAME=/etc/host_hostname"
        networks: 
            - monitor-network
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 10s
            update_config:
                parallelism: 2
                delay: 10s
            resources:
                limits:
                    cpus: '0.10'
                    memory: 128M
                reservations:
                    cpus: '0.10'
                    memory: 64M

    cadvisor:
        image: "google/cadvisor:v0.29.0"
        command:
            - '-docker_only'
        volumes:
            - /var/lib/docker:/var/lib/docker
            - /var/run:/var/run
            - /sys:/sys
            - /:/rootfs
        networks: 
            - monitor-network
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 10s
            update_config:
                parallelism: 2
                delay: 10s
            resources:
                limits:
                    cpus: '0.10'
                    memory: 128M
                reservations:
                    cpus: '0.10'
                    memory: 64M
networks:
  monitor-network:
    external: true
    name: monitor-network
