version: '3.1'
services:
    grafana:
        build: grafana/
        image: "lancekuo/grafana:5.0.0-beta4"
        environment:
            - "GF_SECURITY_ADMIN_PASSWORD=test"
        ports:
            - "3000:3000"
        networks: 
            - prom
        deploy:
            placement:
                constraints:
                    - node.labels.type == internal
            resources:
                limits:
                    cpus: '0.50'
                    memory: 64M
                reservations:
                    cpus: '0.50'
                    memory: 32M
    prom:
        build: prometheus/
        image: "lancekuo/prometheus:2.1.0"
        volumes:
            - "/opt/prometheus:/prometheus"
        ports:
            - "9090:9090"
        networks: 
            - prom
        deploy:
            placement:
                constraints:
                    - node.labels.type == storage
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1024M
                reservations:
                    cpus: '0.50'
                    memory: 128M
    node:
        build: node-exporter/
        image: "lancekuo/node-exporter:0.15.2"
        command: 
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
            - '--collector.textfile.directory=/etc/node-exporter/'
        volumes:
            - /proc:/host/proc
            - /sys:/host/sys
            - /:/rootfs
            - /etc/hostname:/etc/host_hostname
        environment:
            - "HOST_HOSTNAME=/etc/host_hostname"
        networks: 
            - prom
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 10s
            update_config:
                parallelism: 2
                delay: 10s
            resources:
                limits:
                    cpus: '0.10'
                    memory: 32M
                reservations:
                    cpus: '0.10'
                    memory: 16M

    cadvisor:
        image: "google/cadvisor:v0.29.0"
        volumes:
            - /var/lib/docker:/var/lib/docker
            - /var/run:/var/run
            - /sys:/sys
            - /:/rootfs
        networks: 
            - prom
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 10s
            update_config:
                parallelism: 2
                delay: 10s
            resources:
                limits:
                    cpus: '0.10'
                    memory: 128M
                reservations:
                    cpus: '0.10'
                    memory: 64M
networks:
    prom:
        driver: overlay

