version: '3.1'
services:
    influxdb:
        image: "influxdb:0.13"
        ports:
            - "8083:8083"
            - "8086:8086"
        networks: 
            - prom
        deploy:
            placement:
                constraints:
                    - node.labels.type == storage
 
    grafana:
        image: "grafana/grafana:3.1.1"
        ports:
            - "3000:3000"
        networks: 
            - prom
        deploy:
            placement:
                constraints:
                    - node.labels.type == internal
    prom:
        build: prometheus/
        image: "lancekuo/prometheus:1.6.1-1"
        ports:
            - "9090:9090"
        networks: 
            - prom
        deploy:
            placement:
                constraints:
                    - node.labels.type == internal


    node:
        image: "prom/node-exporter"
        command: 
            - '-collector.procfs=/host/proc'
            - '-collector.sysfs=/host/sys'
            - '-collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
        volumes:
            - /proc:/host/proc
            - /sys:/host/sys
            - /:/rootfs
        networks: 
            - prom
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 10s
            update_config:
                parallelism: 2
                delay: 10s

    cadvisor:
        image: "google/cadvisor:latest"
        volumes:
            - /var/lib/docker:/var/lib/docker
            - /var/run:/var/run
            - /sys:/sys
            - /:/rootfs
        networks: 
            - prom
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 10s
            update_config:
                parallelism: 2
                delay: 10s
networks:
    prom:
        driver: overlay

