apiVersion: 1

providers:
- name: 'default'
  orgId: 1
  folder: 'HealthChainRx'
  type: file
  disableDeletion: false
  editable: true
  options:
    path: /etc/grafana/provisioning/dashboards/default
